vich_uploader:
    db_driver: orm

    mappings:
       recipe_image:
           uri_prefix: /uploads/recipes
           upload_destination: '%kernel.project_dir%/public/uploads/recipes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true